### ISSUE TITLE
Interval.java

### ISSUE THREAD

**Issue by axkr** [mhogrefe/qbar#1]
I'm the developer of the [Symja Java computer algebra system](https://bitbucket.org/axelclk/symja_android_library/overview) and I would like to know if you use your project also for such a system or what is the intended purpose?

It seems there are a  lot of similarities to Symja as I'm also using JAS and similar classes.
I found your project because I'm searching for an interval arithmetic class.
As it seems I have to rewrite Interval.java to use it in my project. 
So I'm asking, if there is a more generic approach possible by using interfaces like:
- edu.jas.structure.GcdRingElem
- org.apache.commons.math4.FieldElement

so that it's easier to use for other projects?

**Comment by mhogrefe** [comment]
Hi axkr,

Thanks for taking an interest! I haven't used Symja but it looks very interesting.

I'm only using JAS now because I don't know how to implement polynomial factorization efficiently, but my goal is to eventually have no dependencies on other libraries - this is so that I can learn everything myself. Unfortunately, this does make it difficult for others to use my code.

I've just released my projects under the MIT License, so please feel welcome to fork, copy, or reuse anything you want, as long as you provide attribution.

Best,
Mikhail Hogrefe
